language: php
php:
  - 5.6
  - hhvm


before_install:
  - mysql --version
  - sudo apt-get remove mysql-common mysql-server-5.5
  - sudo apt-get install mysql-server-5.6
  - sudo /etc/init.d/mysql.server start
  - mysql --version
  - mysql -e "create database IF NOT EXISTS mobi2;"
  - cd work
  - pwd
  - whoami
  - cp templates.json.travis templates.json
  - composer self-update
#  - composer install
#  - sh ./bin/deploy/post_install.sh


script:
  - phpunit --configuration ./test/unit/phpunit.dist.xml
  - phpunit --configuration ./test/functional/phpunit.dist.xml


notifications:
  email:
    recipients:
      - alex@flancer64.com
    on_success: always # [always|never|change], default: change
    on_failure: always # [always|never|change], default: change