language: php
php:
  - 5.6
# - hhvm

sudo: required
dist: trusty

before_install:
# Setup MySQL 5.6 on Ubuntu 12.04:
  - mysql --version
#  - sudo apt-get remove mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5
#  - sudo apt-get autoremove
#  - sudo apt-get install libaio1
#  - wget -O mysql-5.6.deb http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.14-debian6.0-x86_64.deb/from/http://cdn.mysql.com/
#  - sudo dpkg -i  mysql-5.6.deb
#  - sudo /etc/init.d/mysql.server start
#  - mysql --version
# Go to working folder, copy templates.json for travis and start composer install process
#  - cd work
#  - mysql -e "create database if not exists mobi2;"
#  - pwd
#  - whoami
#  - cp templates.json.travis templates.json
#  - composer self-update
#  - composer install
#  - sh ./bin/deploy/post_install.sh


script:
  - phpunit --configuration ./test/unit/phpunit.dist.xml
  - phpunit --configuration ./test/functional/phpunit.dist.xml


notifications:
  email:
    recipients:
      - alex@flancer64.com
    on_success: always # [always|never|change], default: change
    on_failure: always # [always|never|change], default: change